[package]
name = "kipuka-hsm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "PKCS#11 HSM abstraction supporting Entrust, Utimaco, Kryoptic, Thales CSP/TCT"

[dependencies]
cryptoki.workspace = true
synta-certificate.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
url.workspace = true
hex.workspace = true
