build-debug:
  extends: .rust-base
  stage: build
  script:
    - cargo build --locked --workspace --all-features

build-release:
  extends: .rust-base
  stage: build
  script:
    - cargo build --locked --workspace --release --all-features
  artifacts:
    paths: [target/release/kipuka, target/release/kipuka-keygen]
    expire_in: 7 days

build-docs:
  extends: .rust-base
  stage: build
  script:
    - cargo doc --locked --workspace --all-features --no-deps
  artifacts:
    paths: [target/doc/]
    expire_in: 7 days
